### ISSUE TITLE
utools can not open 

### ISSUE THREAD

**Issue by GengCen-Qin** [Moeyua/youglish-for-uTools#1]
我将插件下载utools中，但无法正常使用
![image](https://user-images.githubusercontent.com/98941324/185268749-064fd14f-28b7-48ee-8848-9349bed7e693.png)

**Comment by Moeyua** [comment]
https://youglish.com/pronounce/ajax/english?

**Comment by moeyua** [comment]
这个页面看起来是因为 Cloudflare 正在识别你是不是机器人，可以试着多等待一会儿。或者尝试更换机场节点。
